### PR TITLE
WebUI: Specific remove rules changed to single-clicks

### PR DESCRIPTION
**Pull request by mhertz**

### CODE REVIEW

**Comment by mhertz** [comment]
Just small note about this change here isn't perfect(when dirty need focus next field additionally first, or press return, and so just as well could simply double-click, but still more user-friendly for new users imho with this), and I have tried pretty much all by now, and so need hacks as far I can tell, and so if not sensitive to that, or if can improve upon it firstly, then this change here atleast works for true single-clicks of everything in quick tests, but probably not worth it, or need be optimized/made-better firstly, but just for completeness: https://github.com/mhertz/deluge-autoremoveplus/commit/6e4ee8fa05a9a1ca763ba0145def919848251f1a

It looks strange, but has reasons i.e. row selmodel doesn't disclose column, only row, hence need get it from other means, and cellclick event don't work for our purposse. I also previous changed to cell selmodel and could make work without additional listener(cellmousedown), as column available, but decided against because needed then emulate row-selection for userfriendly multi-row rule deletion etc etc. Anyway, just explaining myself little and feel free to ignore of-course, as no biggie this lol :)

**Comment by laur89** [comment]
@mhertz oh shit sorry dude, completely missed your PR! Feel free to re-open if it's still valid!

**Comment by mhertz** [comment]
Much love bro for that kind post :) I just thought no need clutter if maybe seen unfitted or alike, and as wasn't important anyway, so please just look at in feature, if wanted, and no rush obviously. Thanks!

**Comment by laur89** [comment]
So this is to immediately activate/make editable the specific rules with a single click as opposed to double-click?
Have you noticed users struggling with it before or what made you introduce this change in the first place?

Also note lines 461 & 634 are missing one level of indentation.

**Comment by mhertz** [comment]
Yes the specific remove rules is made single-clicks now. In newer extjs there was introduced clicksToMoveEditor(in addition to clicksToEdit), seemingly fixing this behaviour, and I looked at the source and used same idea as they do i.e. a listener and checks for editing, and just had to change the listener and such to make work right for us.

It was reported by one on the forum as broken, don't remember if talked about by others before that honestly, and then another posted workaround to first right-click then left click, and imho is not very intuitive, especially since GTK-UI is single click for these rules, though granted I see a bug there, which i'll look at sometime I think, where currently a call to focus new rule breaks, and hence you need first activate the rule with a click, but is only once, and atleast is showing you that it gets activated so you think to try again imho.

Sorry about the indention, fixed thanks.

Anyway, as said, very low priority thing and not really important, and so please don't hesitate to just close this, if feel isn't suited bro :)

**Comment by laur89** [comment]
If native client has single-click activation, then it'd make sense to keep it consistent 👍🏼

**Comment by mhertz** [comment]
Thank you my friend, forgive the wording please if bad, if need changing then say to me or make yourself thanks, what's easiest for you, and as said, can easily wait of-course - otherwise thanks for talk, see you on the forum :)

**Pull request merged**
